package com.vendertool.common;

public enum DAOFactoryKey {

	ACCOUNT_DAO,
	ACCOUNT_CONFIRMATION_DAO,
	ADDRESS_DAO,
	PASSWORD_HISTORY_DAO,
	IMAGE_DAO,
	LISTING_DAO,
	LISTING_VARIATION_DAO,
	PRODUCT_DAO,
	PRODUCT_VARIATION_DAO,
	PRODUCT_ATTRIBUTE_DAO,
	FILE_DAO,
	JOB_DAO,
	TASK_DAO
	;
	
}