package com.vendertool.fps.dal.task;

// Generated Aug 29, 2013 8:28:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", catalog = "batchdb")
public class Task implements java.io.Serializable {

	private Long taskId;
	private long jobId;
	private String requestGroupId;
	private Long accountId;
	private Long requestFileId;
	private Long recordId;
	private byte[] request;
	private byte[] response;
	private Byte status;
	private String isoCountryCode;
	private Date createdDate;
	private Date lastModifiedDate;

	public Task() {
	}

	public Task(long jobId, String requestGroupId, byte[] request,
			Date createdDate, Date lastModifiedDate) {
		this.jobId = jobId;
		this.requestGroupId = requestGroupId;
		this.request = request;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Task(long jobId, String requestGroupId, Long accountId,
			Long requestFileId, Long recordId, byte[] request, byte[] response,
			Byte status, String isoCountryCode, Date createdDate,
			Date lastModifiedDate) {
		this.jobId = jobId;
		this.requestGroupId = requestGroupId;
		this.accountId = accountId;
		this.requestFileId = requestFileId;
		this.recordId = recordId;
		this.request = request;
		this.response = response;
		this.status = status;
		this.isoCountryCode = isoCountryCode;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_id", unique = true, nullable = false)
	public Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	@Column(name = "job_id", nullable = false)
	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	@Column(name = "request_group_id", nullable = false, length = 64)
	public String getRequestGroupId() {
		return this.requestGroupId;
	}

	public void setRequestGroupId(String requestGroupId) {
		this.requestGroupId = requestGroupId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "request_file_id")
	public Long getRequestFileId() {
		return this.requestFileId;
	}

	public void setRequestFileId(Long requestFileId) {
		this.requestFileId = requestFileId;
	}

	@Column(name = "record_id")
	public Long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "request", nullable = false)
	public byte[] getRequest() {
		return this.request;
	}

	public void setRequest(byte[] request) {
		this.request = request;
	}

	@Column(name = "response")
	public byte[] getResponse() {
		return this.response;
	}

	public void setResponse(byte[] response) {
		this.response = response;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "iso_country_code", length = 3)
	public String getIsoCountryCode() {
		return this.isoCountryCode;
	}

	public void setIsoCountryCode(String isoCountryCode) {
		this.isoCountryCode = isoCountryCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
