package com.vendertool.fps.dal.sequenceData;

// Generated Aug 29, 2013 8:28:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SequenceData generated by hbm2java
 */
@Entity
@Table(name = "sequence_data", catalog = "batchdb")
public class SequenceData implements java.io.Serializable {

	private String sequenceName;
	private int increment;
	private int minValue;
	private long maxValue;
	private long curValue;
	private byte isRecycle;
	private Date createdDate;
	private Date lastModifiedDate;

	public SequenceData() {
	}

	public SequenceData(String sequenceName, int increment, int minValue,
			long maxValue, long curValue, byte isRecycle) {
		this.sequenceName = sequenceName;
		this.increment = increment;
		this.minValue = minValue;
		this.maxValue = maxValue;
		this.curValue = curValue;
		this.isRecycle = isRecycle;
	}

	public SequenceData(String sequenceName, int increment, int minValue,
			long maxValue, long curValue, byte isRecycle, Date createdDate,
			Date lastModifiedDate) {
		this.sequenceName = sequenceName;
		this.increment = increment;
		this.minValue = minValue;
		this.maxValue = maxValue;
		this.curValue = curValue;
		this.isRecycle = isRecycle;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "sequence_name", unique = true, nullable = false, length = 128)
	public String getSequenceName() {
		return this.sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	@Column(name = "increment", nullable = false)
	public int getIncrement() {
		return this.increment;
	}

	public void setIncrement(int increment) {
		this.increment = increment;
	}

	@Column(name = "min_value", nullable = false)
	public int getMinValue() {
		return this.minValue;
	}

	public void setMinValue(int minValue) {
		this.minValue = minValue;
	}

	@Column(name = "max_value", nullable = false)
	public long getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(long maxValue) {
		this.maxValue = maxValue;
	}

	@Column(name = "cur_value", nullable = false)
	public long getCurValue() {
		return this.curValue;
	}

	public void setCurValue(long curValue) {
		this.curValue = curValue;
	}

	@Column(name = "is_recycle", nullable = false)
	public byte getIsRecycle() {
		return this.isRecycle;
	}

	public void setIsRecycle(byte isRecycle) {
		this.isRecycle = isRecycle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
