package com.vendertool.inventory.dal.image;

// Generated Aug 29, 2013 5:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "invdb")
public class Image implements java.io.Serializable {

	private Long imageId;
	private Long accountId;
	private String imageName;
	private Byte sortOrderId;
	private long refId;
	private Byte refType;
	private Byte imageFormat;
	private String hostedUrl;
	private String hash;
	private String size;
	private Date createdDate;
	private Date lastModifiedDate;

	public Image() {
	}

	public Image(long refId) {
		this.refId = refId;
	}

	public Image(Long accountId, String imageName, Byte sortOrderId,
			long refId, Byte refType, Byte imageFormat, String hostedUrl,
			String hash, String size, Date createdDate, Date lastModifiedDate) {
		this.accountId = accountId;
		this.imageName = imageName;
		this.sortOrderId = sortOrderId;
		this.refId = refId;
		this.refType = refType;
		this.imageFormat = imageFormat;
		this.hostedUrl = hostedUrl;
		this.hash = hash;
		this.size = size;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_id", unique = true, nullable = false)
	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "image_name", length = 64)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "sort_order_id")
	public Byte getSortOrderId() {
		return this.sortOrderId;
	}

	public void setSortOrderId(Byte sortOrderId) {
		this.sortOrderId = sortOrderId;
	}

	@Column(name = "ref_id", nullable = false)
	public long getRefId() {
		return this.refId;
	}

	public void setRefId(long refId) {
		this.refId = refId;
	}

	@Column(name = "ref_type")
	public Byte getRefType() {
		return this.refType;
	}

	public void setRefType(Byte refType) {
		this.refType = refType;
	}

	@Column(name = "image_format")
	public Byte getImageFormat() {
		return this.imageFormat;
	}

	public void setImageFormat(Byte imageFormat) {
		this.imageFormat = imageFormat;
	}

	@Column(name = "hosted_url", length = 1028)
	public String getHostedUrl() {
		return this.hostedUrl;
	}

	public void setHostedUrl(String hostedUrl) {
		this.hostedUrl = hostedUrl;
	}

	@Column(name = "hash", length = 64)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "size", length = 32)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
