package com.vendertool.registration.dal.accountConfirmation;

// Generated Aug 26, 2013 10:07:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountConfirmation generated by hbm2java
 */
@Entity
@Table(name = "account_confirmation", catalog = "invdb")
public class AccountConfirmation implements java.io.Serializable {

	private long accountConfirmationId;
	private Long accountId;
	private Short confirmationCode;
	private Byte numberOfAttempts;
	private String sessionId;
	private Date confirmationDate;
	private Date expiryDate;
	private Date createdDate;
	private Date lastModifiedDate;
	private Byte lastModifiedApp;

	public AccountConfirmation() {
	}

	public AccountConfirmation(long accountConfirmationId) {
		this.accountConfirmationId = accountConfirmationId;
	}

	public AccountConfirmation(long accountConfirmationId, Long accountId,
			Short confirmationCode, Byte numberOfAttempts, String sessionId,
			Date confirmationDate, Date expiryDate, Date createdDate,
			Date lastModifiedDate, Byte lastModifiedApp) {
		this.accountConfirmationId = accountConfirmationId;
		this.accountId = accountId;
		this.confirmationCode = confirmationCode;
		this.numberOfAttempts = numberOfAttempts;
		this.sessionId = sessionId;
		this.confirmationDate = confirmationDate;
		this.expiryDate = expiryDate;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedApp = lastModifiedApp;
	}

	@Id
	@Column(name = "account_confirmation_id", unique = true, nullable = false)
	public long getAccountConfirmationId() {
		return this.accountConfirmationId;
	}

	public void setAccountConfirmationId(long accountConfirmationId) {
		this.accountConfirmationId = accountConfirmationId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "confirmation_code")
	public Short getConfirmationCode() {
		return this.confirmationCode;
	}

	public void setConfirmationCode(Short confirmationCode) {
		this.confirmationCode = confirmationCode;
	}

	@Column(name = "number_of_attempts")
	public Byte getNumberOfAttempts() {
		return this.numberOfAttempts;
	}

	public void setNumberOfAttempts(Byte numberOfAttempts) {
		this.numberOfAttempts = numberOfAttempts;
	}

	@Column(name = "session_id", length = 1024)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "confirmation_date", length = 19)
	public Date getConfirmationDate() {
		return this.confirmationDate;
	}

	public void setConfirmationDate(Date confirmationDate) {
		this.confirmationDate = confirmationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "last_modified_app")
	public Byte getLastModifiedApp() {
		return this.lastModifiedApp;
	}

	public void setLastModifiedApp(Byte lastModifiedApp) {
		this.lastModifiedApp = lastModifiedApp;
	}

}
