package com.dal.dao;

// Generated May 26, 2013 5:25:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BatchJobId generated by hbm2java
 */
@Embeddable
public class BatchJobId implements java.io.Serializable {

	private long batchJobId;
	private long fileId;

	public BatchJobId() {
	}

	public BatchJobId(long batchJobId, long fileId) {
		this.batchJobId = batchJobId;
		this.fileId = fileId;
	}

	@Column(name = "BATCH_JOB_ID", nullable = false)
	public long getBatchJobId() {
		return this.batchJobId;
	}

	public void setBatchJobId(long batchJobId) {
		this.batchJobId = batchJobId;
	}

	@Column(name = "FILE_ID", nullable = false)
	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BatchJobId))
			return false;
		BatchJobId castOther = (BatchJobId) other;

		return (this.getBatchJobId() == castOther.getBatchJobId())
				&& (this.getFileId() == castOther.getFileId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBatchJobId();
		result = 37 * result + (int) this.getFileId();
		return result;
	}

}
