package com.dal.dao;

// Generated May 26, 2013 5:25:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchJob generated by hbm2java
 */
@Entity
@Table(name = "batch_job", catalog = "PRODUCTDB")
public class BatchJob implements java.io.Serializable {

	private static final long serialVersionUID = 8435816300335855973L;
	
	private BatchJobId id;
	private Long accountId;
	private Integer siteId;
	private String fileName;
	private Byte status;
	private String reqLocation;
	private String resLocation;
	private String sellerNotes;
	private Byte usecase;
	private Long totalRecords;
	private Long processedRecords;
	private Long errorCount;
	private Date createDate;
	private Date lastModifiedDate;

	public BatchJob() {
	}

	public BatchJob(BatchJobId id) {
		this.id = id;
	}

	public BatchJob(BatchJobId id, Long accountId, Integer siteId,
			String fileName, Byte status, String reqLocation,
			String resLocation, String sellerNotes, Byte usecase,
			Long totalRecords, Long processedRecords, Long errorCount,
			Date createDate, Date lastModifiedDate) {
		this.id = id;
		this.accountId = accountId;
		this.siteId = siteId;
		this.fileName = fileName;
		this.status = status;
		this.reqLocation = reqLocation;
		this.resLocation = resLocation;
		this.sellerNotes = sellerNotes;
		this.usecase = usecase;
		this.totalRecords = totalRecords;
		this.processedRecords = processedRecords;
		this.errorCount = errorCount;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "batchJobId", column = @Column(name = "BATCH_JOB_ID", nullable = false)),
			@AttributeOverride(name = "fileId", column = @Column(name = "FILE_ID", nullable = false)) })
	public BatchJobId getId() {
		return this.id;
	}

	public void setId(BatchJobId id) {
		this.id = id;
	}

	@Column(name = "ACCOUNT_ID")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "SITE_ID")
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Column(name = "FILE_NAME", length = 256)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "REQ_LOCATION", length = 512)
	public String getReqLocation() {
		return this.reqLocation;
	}

	public void setReqLocation(String reqLocation) {
		this.reqLocation = reqLocation;
	}

	@Column(name = "RES_LOCATION", length = 512)
	public String getResLocation() {
		return this.resLocation;
	}

	public void setResLocation(String resLocation) {
		this.resLocation = resLocation;
	}

	@Column(name = "SELLER_NOTES", length = 512)
	public String getSellerNotes() {
		return this.sellerNotes;
	}

	public void setSellerNotes(String sellerNotes) {
		this.sellerNotes = sellerNotes;
	}

	@Column(name = "USECASE")
	public Byte getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Byte usecase) {
		this.usecase = usecase;
	}

	@Column(name = "TOTAL_RECORDS")
	public Long getTotalRecords() {
		return this.totalRecords;
	}

	public void setTotalRecords(Long totalRecords) {
		this.totalRecords = totalRecords;
	}

	@Column(name = "PROCESSED_RECORDS")
	public Long getProcessedRecords() {
		return this.processedRecords;
	}

	public void setProcessedRecords(Long processedRecords) {
		this.processedRecords = processedRecords;
	}

	@Column(name = "ERROR_COUNT")
	public Long getErrorCount() {
		return this.errorCount;
	}

	public void setErrorCount(Long errorCount) {
		this.errorCount = errorCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
