package com.dal.dao;

// Generated May 17, 2013 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "PRODUCTDB")
public class Image implements java.io.Serializable {

	private long imageId;
	private Long accountId;
	private String imageName;
	private Byte sortOrderId;
	private Long refId;
	private Byte refType;
	private Byte imageFormat;
	private String hostedUrl;
	private String hash;
	private String size;
	private Date lastModifiedDate;
	private Date createDate;

	public Image() {
	}

	public Image(long imageId) {
		this.imageId = imageId;
	}

	public Image(long imageId, Long accountId, String imageName,
			Byte sortOrderId, Long refId, Byte refType, Byte imageFormat,
			String hostedUrl, String hash, String size, Date lastModifiedDate,
			Date createDate) {
		this.imageId = imageId;
		this.accountId = accountId;
		this.imageName = imageName;
		this.sortOrderId = sortOrderId;
		this.refId = refId;
		this.refType = refType;
		this.imageFormat = imageFormat;
		this.hostedUrl = hostedUrl;
		this.hash = hash;
		this.size = size;
		this.lastModifiedDate = lastModifiedDate;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "IMAGE_ID", unique = true, nullable = false)
	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	@Column(name = "ACCOUNT_ID")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "IMAGE_NAME", length = 64)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "SORT_ORDER_ID")
	public Byte getSortOrderId() {
		return this.sortOrderId;
	}

	public void setSortOrderId(Byte sortOrderId) {
		this.sortOrderId = sortOrderId;
	}

	@Column(name = "REF_ID")
	public Long getRefId() {
		return this.refId;
	}

	public void setRefId(Long refId) {
		this.refId = refId;
	}

	@Column(name = "REF_TYPE")
	public Byte getRefType() {
		return this.refType;
	}

	public void setRefType(Byte refType) {
		this.refType = refType;
	}

	@Column(name = "IMAGE_FORMAT")
	public Byte getImageFormat() {
		return this.imageFormat;
	}

	public void setImageFormat(Byte imageFormat) {
		this.imageFormat = imageFormat;
	}

	@Column(name = "HOSTED_URL", length = 1028)
	public String getHostedUrl() {
		return this.hostedUrl;
	}

	public void setHostedUrl(String hostedUrl) {
		this.hostedUrl = hostedUrl;
	}

	@Column(name = "HASH", length = 64)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "SIZE", length = 32)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
