package com.dal.dao;

// Generated May 17, 2013 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductVariation generated by hbm2java
 */
@Entity
@Table(name = "product_variation", catalog = "PRODUCTDB")
public class ProductVariation implements java.io.Serializable {

	private long productVariationsId;
	private String title;
	private String variationName;
	private String variationValue;
	private Long productId;
	private String sku;
	private Integer availbleQuantity;
	private BigDecimal price;
	private Date lastModifiedDate;
	private Date createDate;

	public ProductVariation() {
	}

	public ProductVariation(long productVariationsId) {
		this.productVariationsId = productVariationsId;
	}

	public ProductVariation(long productVariationsId, String title,String variationName,String variationValue,
			Long productId, String sku, Integer availbleQuantity,
			BigDecimal price, Date lastModifiedDate, Date createDate) {
		this.productVariationsId = productVariationsId;
		this.title = title;
		this.variationName = variationName;
		this.variationValue = variationValue;
		this.productId = productId;
		this.sku = sku;
		this.availbleQuantity = availbleQuantity;
		this.price = price;
		this.lastModifiedDate = lastModifiedDate;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "PRODUCT_VARIATIONS_ID", unique = true, nullable = false)
	public long getProductVariationsId() {
		return this.productVariationsId;
	}

	public void setProductVariationsId(long productVariationsId) {
		this.productVariationsId = productVariationsId;
	}

	@Column(name = "TITLE", length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "VARIATION_NAME", length = 45)
	public String getVariationName() {
		return variationName;
	}

	public void setVariationName(String variationName) {
		this.variationName = variationName;
	}

	@Column(name = "VARIATION_VALUE", length = 45)
	public String getVariationValue() {
		return variationValue;
	}

	public void setVariationValue(String variationValue) {
		this.variationValue = variationValue;
	}

	@Column(name = "PRODUCT_ID")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "SKU", length = 64)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "AVAILBLE_QUANTITY")
	public Integer getAvailbleQuantity() {
		return this.availbleQuantity;
	}

	public void setAvailbleQuantity(Integer availbleQuantity) {
		this.availbleQuantity = availbleQuantity;
	}

	@Column(name = "PRICE", precision = 18, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
