package com.dal.dao;

// Generated May 17, 2013 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute", catalog = "PRODUCTDB")
public class ProductAttribute implements java.io.Serializable {

	private long productAttributeId;
	private String attrName;
	private Long productSpecificationId;
	private String attrCharValue;
	private BigDecimal attrNumValue;
	private Date attrDateValue;
	private Byte attrDataType;
	private Date lastModifiedDate;
	private Date createdDate;

	public ProductAttribute() {
	}

	public ProductAttribute(long productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	public ProductAttribute(long productAttributeId, String attrName,
			Long productSpecificationId, String attrCharValue,
			BigDecimal attrNumValue, Date attrDateValue, Byte attrDataType,
			Date lastModifiedDate, Date createdDate) {
		this.productAttributeId = productAttributeId;
		this.attrName = attrName;
		this.productSpecificationId = productSpecificationId;
		this.attrCharValue = attrCharValue;
		this.attrNumValue = attrNumValue;
		this.attrDateValue = attrDateValue;
		this.attrDataType = attrDataType;
		this.lastModifiedDate = lastModifiedDate;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "PRODUCT_ATTRIBUTE_ID", unique = true, nullable = false)
	public long getProductAttributeId() {
		return this.productAttributeId;
	}

	public void setProductAttributeId(long productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	@Column(name = "ATTR_NAME", length = 64)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	@Column(name = "PRODUCT_SPECIFICATION_ID")
	public Long getProductSpecificationId() {
		return this.productSpecificationId;
	}

	public void setProductSpecificationId(Long productSpecificationId) {
		this.productSpecificationId = productSpecificationId;
	}

	@Column(name = "ATTR_CHAR_VALUE", length = 64)
	public String getAttrCharValue() {
		return this.attrCharValue;
	}

	public void setAttrCharValue(String attrCharValue) {
		this.attrCharValue = attrCharValue;
	}

	@Column(name = "ATTR_NUM_VALUE", precision = 18, scale = 4)
	public BigDecimal getAttrNumValue() {
		return this.attrNumValue;
	}

	public void setAttrNumValue(BigDecimal attrNumValue) {
		this.attrNumValue = attrNumValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATTR_DATE_VALUE", length = 19)
	public Date getAttrDateValue() {
		return this.attrDateValue;
	}

	public void setAttrDateValue(Date attrDateValue) {
		this.attrDateValue = attrDateValue;
	}

	@Column(name = "ATTR_DATA_TYPE")
	public Byte getAttrDataType() {
		return this.attrDataType;
	}

	public void setAttrDataType(Byte attrDataType) {
		this.attrDataType = attrDataType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
