package com.dal.dao;

// Generated May 17, 2013 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductSpecification generated by hbm2java
 */
@Entity
@Table(name = "product_specification", catalog = "PRODUCTDB")
public class ProductSpecification implements java.io.Serializable {

	private long productSpecificationId;
	private long refId;
	private Byte refType;
	private Byte weightUnit;
	private BigDecimal weight;
	private Byte dimensionUnit;
	private BigDecimal width;
	private BigDecimal length;
	private BigDecimal height;
	private Date lastModifiedDate;
	private Date createDate;

	public ProductSpecification() {
	}

	public ProductSpecification(long productSpecificationId, long refId) {
		this.productSpecificationId = productSpecificationId;
		this.refId = refId;
	}

	public ProductSpecification(long productSpecificationId, long refId,
			Byte refType, Byte weightUnit, BigDecimal weight,
			Byte dimensionUnit, BigDecimal width, BigDecimal length,
			BigDecimal height, Date lastModifiedDate, Date createDate) {
		this.productSpecificationId = productSpecificationId;
		this.refId = refId;
		this.refType = refType;
		this.weightUnit = weightUnit;
		this.weight = weight;
		this.dimensionUnit = dimensionUnit;
		this.width = width;
		this.length = length;
		this.height = height;
		this.lastModifiedDate = lastModifiedDate;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "PRODUCT_SPECIFICATION_ID", unique = true, nullable = false)
	public long getProductSpecificationId() {
		return this.productSpecificationId;
	}

	public void setProductSpecificationId(long productSpecificationId) {
		this.productSpecificationId = productSpecificationId;
	}

	@Column(name = "REF_ID", nullable = false)
	public long getRefId() {
		return this.refId;
	}

	public void setRefId(long refId) {
		this.refId = refId;
	}

	@Column(name = "REF_TYPE")
	public Byte getRefType() {
		return this.refType;
	}

	public void setRefType(Byte refType) {
		this.refType = refType;
	}

	@Column(name = "WEIGHT_UNIT")
	public Byte getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(Byte weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "WEIGHT", precision = 8)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "DIMENSION_UNIT")
	public Byte getDimensionUnit() {
		return this.dimensionUnit;
	}

	public void setDimensionUnit(Byte dimensionUnit) {
		this.dimensionUnit = dimensionUnit;
	}

	@Column(name = "WIDTH", precision = 8)
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	@Column(name = "LENGTH", precision = 8)
	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	@Column(name = "HEIGHT", precision = 8)
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
