package com.vendertool.registration.dal.address;

// Generated Aug 26, 2013 10:07:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "invdb")
public class Address implements java.io.Serializable {

	private Long addressId;
	private byte useCase;
	private Byte addrType;
	private String contactFirstName;
	private String contactLastName;
	private String companyName;
	private String addrLn1;
	private String addrLn2;
	private String addrLn3;
	private String city;
	private String state;
	private Byte countryCodeIso3;
	private String postalCode;
	private Byte status;
	private Date createdDate;
	private Date lastModifiedDate;

	public Address() {
	}

	public Address(byte useCase) {
		this.useCase = useCase;
	}

	public Address(byte useCase, Byte addrType, String contactFirstName,
			String contactLastName, String companyName, String addrLn1,
			String addrLn2, String addrLn3, String city, String state,
			Byte countryCodeIso3, String postalCode, Byte status,
			Date createdDate, Date lastModifiedDate) {
		this.useCase = useCase;
		this.addrType = addrType;
		this.contactFirstName = contactFirstName;
		this.contactLastName = contactLastName;
		this.companyName = companyName;
		this.addrLn1 = addrLn1;
		this.addrLn2 = addrLn2;
		this.addrLn3 = addrLn3;
		this.city = city;
		this.state = state;
		this.countryCodeIso3 = countryCodeIso3;
		this.postalCode = postalCode;
		this.status = status;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	@Column(name = "use_case", nullable = false)
	public byte getUseCase() {
		return this.useCase;
	}

	public void setUseCase(byte useCase) {
		this.useCase = useCase;
	}

	@Column(name = "addr_type")
	public Byte getAddrType() {
		return this.addrType;
	}

	public void setAddrType(Byte addrType) {
		this.addrType = addrType;
	}

	@Column(name = "contact_first_name", length = 64)
	public String getContactFirstName() {
		return this.contactFirstName;
	}

	public void setContactFirstName(String contactFirstName) {
		this.contactFirstName = contactFirstName;
	}

	@Column(name = "contact_last_name", length = 64)
	public String getContactLastName() {
		return this.contactLastName;
	}

	public void setContactLastName(String contactLastName) {
		this.contactLastName = contactLastName;
	}

	@Column(name = "company_name", length = 64)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "addr_ln1", length = 128)
	public String getAddrLn1() {
		return this.addrLn1;
	}

	public void setAddrLn1(String addrLn1) {
		this.addrLn1 = addrLn1;
	}

	@Column(name = "addr_ln2", length = 128)
	public String getAddrLn2() {
		return this.addrLn2;
	}

	public void setAddrLn2(String addrLn2) {
		this.addrLn2 = addrLn2;
	}

	@Column(name = "addr_ln3", length = 128)
	public String getAddrLn3() {
		return this.addrLn3;
	}

	public void setAddrLn3(String addrLn3) {
		this.addrLn3 = addrLn3;
	}

	@Column(name = "city", length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 64)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country_code_iso3")
	public Byte getCountryCodeIso3() {
		return this.countryCodeIso3;
	}

	public void setCountryCodeIso3(Byte countryCodeIso3) {
		this.countryCodeIso3 = countryCodeIso3;
	}

	@Column(name = "postal_code", length = 32)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
