package com.vendertool.listing.dal.listing;

// Generated Aug 29, 2013 5:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Listing generated by hbm2java
 */
@Entity
@Table(name = "listing", catalog = "invdb")
public class Listing implements java.io.Serializable {

	private Long listingId;
	private long productId;
	private Long accountId;
	private long masterTemplateId;
	private Integer quantity;
	private String categoryId;
	private Byte marketplaceId;
	private String marketplaceItemId;
	private Byte currencyId;
	private BigDecimal fixedPrice;
	private BigDecimal auctionStartPrice;
	private BigDecimal auctionCurrentPrice;
	private BigDecimal auctionReservedPrice;
	private String warranty;
	private Date itemStartTime;
	private Date itemEndTime;
	private Long parentItemId;
	private String condition;
	private Date createdDate;
	private Date lastModifiedDate;
	private Byte lastModifiedApp;

	public Listing() {
	}

	public Listing(long productId, long masterTemplateId) {
		this.productId = productId;
		this.masterTemplateId = masterTemplateId;
	}

	public Listing(long productId, Long accountId, long masterTemplateId,
			Integer quantity, String categoryId, Byte marketplaceId,
			String marketplaceItemId, Byte currencyId, BigDecimal fixedPrice,
			BigDecimal auctionStartPrice, BigDecimal auctionCurrentPrice,
			BigDecimal auctionReservedPrice, String warranty,
			Date itemStartTime, Date itemEndTime, Long parentItemId,
			String condition, Date createdDate, Date lastModifiedDate,
			Byte lastModifiedApp) {
		this.productId = productId;
		this.accountId = accountId;
		this.masterTemplateId = masterTemplateId;
		this.quantity = quantity;
		this.categoryId = categoryId;
		this.marketplaceId = marketplaceId;
		this.marketplaceItemId = marketplaceItemId;
		this.currencyId = currencyId;
		this.fixedPrice = fixedPrice;
		this.auctionStartPrice = auctionStartPrice;
		this.auctionCurrentPrice = auctionCurrentPrice;
		this.auctionReservedPrice = auctionReservedPrice;
		this.warranty = warranty;
		this.itemStartTime = itemStartTime;
		this.itemEndTime = itemEndTime;
		this.parentItemId = parentItemId;
		this.condition = condition;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedApp = lastModifiedApp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "listing_id", unique = true, nullable = false)
	public Long getListingId() {
		return this.listingId;
	}

	public void setListingId(Long listingId) {
		this.listingId = listingId;
	}

	@Column(name = "product_id", nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "master_template_id", nullable = false)
	public long getMasterTemplateId() {
		return this.masterTemplateId;
	}

	public void setMasterTemplateId(long masterTemplateId) {
		this.masterTemplateId = masterTemplateId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "category_id", length = 64)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "marketplace_id")
	public Byte getMarketplaceId() {
		return this.marketplaceId;
	}

	public void setMarketplaceId(Byte marketplaceId) {
		this.marketplaceId = marketplaceId;
	}

	@Column(name = "marketplace_item_id", length = 45)
	public String getMarketplaceItemId() {
		return this.marketplaceItemId;
	}

	public void setMarketplaceItemId(String marketplaceItemId) {
		this.marketplaceItemId = marketplaceItemId;
	}

	@Column(name = "currency_id")
	public Byte getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Byte currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "fixed_price", precision = 18, scale = 4)
	public BigDecimal getFixedPrice() {
		return this.fixedPrice;
	}

	public void setFixedPrice(BigDecimal fixedPrice) {
		this.fixedPrice = fixedPrice;
	}

	@Column(name = "auction_start_price", precision = 18, scale = 4)
	public BigDecimal getAuctionStartPrice() {
		return this.auctionStartPrice;
	}

	public void setAuctionStartPrice(BigDecimal auctionStartPrice) {
		this.auctionStartPrice = auctionStartPrice;
	}

	@Column(name = "auction_current_price", precision = 18, scale = 4)
	public BigDecimal getAuctionCurrentPrice() {
		return this.auctionCurrentPrice;
	}

	public void setAuctionCurrentPrice(BigDecimal auctionCurrentPrice) {
		this.auctionCurrentPrice = auctionCurrentPrice;
	}

	@Column(name = "auction_reserved_price", precision = 18, scale = 4)
	public BigDecimal getAuctionReservedPrice() {
		return this.auctionReservedPrice;
	}

	public void setAuctionReservedPrice(BigDecimal auctionReservedPrice) {
		this.auctionReservedPrice = auctionReservedPrice;
	}

	@Column(name = "warranty", length = 2000)
	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "item_start_time", length = 19)
	public Date getItemStartTime() {
		return this.itemStartTime;
	}

	public void setItemStartTime(Date itemStartTime) {
		this.itemStartTime = itemStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "item_end_time", length = 19)
	public Date getItemEndTime() {
		return this.itemEndTime;
	}

	public void setItemEndTime(Date itemEndTime) {
		this.itemEndTime = itemEndTime;
	}

	@Column(name = "parent_item_id")
	public Long getParentItemId() {
		return this.parentItemId;
	}

	public void setParentItemId(Long parentItemId) {
		this.parentItemId = parentItemId;
	}

	@Column(name = "condition", length = 64)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "last_modified_app")
	public Byte getLastModifiedApp() {
		return this.lastModifiedApp;
	}

	public void setLastModifiedApp(Byte lastModifiedApp) {
		this.lastModifiedApp = lastModifiedApp;
	}

}
