package com.vendertool.inventory.dal.productAttribute;

// Generated Aug 29, 2013 5:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute", catalog = "invdb")
public class ProductAttribute implements java.io.Serializable {

	private Long productAttributeId;
	private Long refId;
	private Byte refType;
	private String attrName;
	private String attrCharValue;
	private BigDecimal attrNumValue;
	private Date attrDateValue;
	private Byte attrValueType;
	private Date createdDate;
	private Date lastModifiedDate;

	public ProductAttribute() {
	}

	public ProductAttribute(Long refId, Byte refType, String attrName,
			String attrCharValue, BigDecimal attrNumValue, Date attrDateValue,
			Byte attrValueType, Date createdDate, Date lastModifiedDate) {
		this.refId = refId;
		this.refType = refType;
		this.attrName = attrName;
		this.attrCharValue = attrCharValue;
		this.attrNumValue = attrNumValue;
		this.attrDateValue = attrDateValue;
		this.attrValueType = attrValueType;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_attribute_id", unique = true, nullable = false)
	public Long getProductAttributeId() {
		return this.productAttributeId;
	}

	public void setProductAttributeId(Long productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	@Column(name = "ref_id")
	public Long getRefId() {
		return this.refId;
	}

	public void setRefId(Long refId) {
		this.refId = refId;
	}

	@Column(name = "ref_type")
	public Byte getRefType() {
		return this.refType;
	}

	public void setRefType(Byte refType) {
		this.refType = refType;
	}

	@Column(name = "attr_name", length = 64)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	@Column(name = "attr_char_value", length = 512)
	public String getAttrCharValue() {
		return this.attrCharValue;
	}

	public void setAttrCharValue(String attrCharValue) {
		this.attrCharValue = attrCharValue;
	}

	@Column(name = "attr_num_value", precision = 18, scale = 4)
	public BigDecimal getAttrNumValue() {
		return this.attrNumValue;
	}

	public void setAttrNumValue(BigDecimal attrNumValue) {
		this.attrNumValue = attrNumValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "attr_date_value", length = 19)
	public Date getAttrDateValue() {
		return this.attrDateValue;
	}

	public void setAttrDateValue(Date attrDateValue) {
		this.attrDateValue = attrDateValue;
	}

	@Column(name = "attr_value_type")
	public Byte getAttrValueType() {
		return this.attrValueType;
	}

	public void setAttrValueType(Byte attrValueType) {
		this.attrValueType = attrValueType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
