package com.vendertool.listing.dal.listingVariation;

// Generated Aug 29, 2013 5:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListingVariation generated by hbm2java
 */
@Entity
@Table(name = "listing_variation", catalog = "invdb")
public class ListingVariation implements java.io.Serializable {

	private Long listingVariationId;
	private Long listingId;
	private Long productVariationId;
	private Integer quantity;
	private BigDecimal price;
	private String condition;
	private Date lastModifiedDate;
	private Byte lastModifiedApp;
	private Date createdDate;

	public ListingVariation() {
	}

	public ListingVariation(Long listingId, Long productVariationId,
			Integer quantity, BigDecimal price, String condition,
			Date lastModifiedDate, Byte lastModifiedApp, Date createdDate) {
		this.listingId = listingId;
		this.productVariationId = productVariationId;
		this.quantity = quantity;
		this.price = price;
		this.condition = condition;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedApp = lastModifiedApp;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "listing_variation_id", unique = true, nullable = false)
	public Long getListingVariationId() {
		return this.listingVariationId;
	}

	public void setListingVariationId(Long listingVariationId) {
		this.listingVariationId = listingVariationId;
	}

	@Column(name = "listing_id")
	public Long getListingId() {
		return this.listingId;
	}

	public void setListingId(Long listingId) {
		this.listingId = listingId;
	}

	@Column(name = "product_variation_id")
	public Long getProductVariationId() {
		return this.productVariationId;
	}

	public void setProductVariationId(Long productVariationId) {
		this.productVariationId = productVariationId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 18)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "condition", length = 64)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "last_modified_app")
	public Byte getLastModifiedApp() {
		return this.lastModifiedApp;
	}

	public void setLastModifiedApp(Byte lastModifiedApp) {
		this.lastModifiedApp = lastModifiedApp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
