package com.vendertool.listing.helper;

public enum ListingHelperTypeEnum {
	ADD_LISTING, 
	GET_LISTING, 
	VERIFY_LISTING, 
	END_LISTING, 
	DUPLICATE_LISTING, 
	ADJUST_LISTING_QUANTITY, 
	UPDATE_LISTING, 
	UPDATE_LISTING_PRICE_QTY, 
	GET_LISTING_PRICE_QTY, 
	GET_AUCTION_BID_COUNT, 
	GET_AUCTION_HIGH_BIDDER;
}