package com.dal.dao;

// Generated May 26, 2013 5:21:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductClassification generated by hbm2java
 */
@Entity
@Table(name = "product_classification", catalog = "PRODUCTDB")
public class ProductClassification implements java.io.Serializable {

	private long classificationId;
	private String classificationName;
	private Integer marketId;
	private String marketRefId;
	private Date createDate;
	private Date lastModifiedDate;
	private Byte lastModifiedApp;

	public ProductClassification() {
	}

	public ProductClassification(long classificationId) {
		this.classificationId = classificationId;
	}

	public ProductClassification(long classificationId,
			String classificationName, Integer marketId, String marketRefId,
			Date createDate, Date lastModifiedDate, Byte lastModifiedApp) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
		this.marketId = marketId;
		this.marketRefId = marketRefId;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedApp = lastModifiedApp;
	}

	@Id
	@Column(name = "CLASSIFICATION_ID", unique = true, nullable = false)
	public long getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(long classificationId) {
		this.classificationId = classificationId;
	}

	@Column(name = "CLASSIFICATION_NAME", length = 45)
	public String getClassificationName() {
		return this.classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	@Column(name = "MARKET_ID")
	public Integer getMarketId() {
		return this.marketId;
	}

	public void setMarketId(Integer marketId) {
		this.marketId = marketId;
	}

	@Column(name = "MARKET_REF_ID", length = 45)
	public String getMarketRefId() {
		return this.marketRefId;
	}

	public void setMarketRefId(String marketRefId) {
		this.marketRefId = marketRefId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "LAST_MODIFIED_APP")
	public Byte getLastModifiedApp() {
		return this.lastModifiedApp;
	}

	public void setLastModifiedApp(Byte lastModifiedApp) {
		this.lastModifiedApp = lastModifiedApp;
	}

}
