package com.dal.dao;

// Generated May 26, 2013 1:11:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingPolicy generated by hbm2java
 */
@Entity
@Table(name = "shipping_policy", catalog = "PRODUCTDB")
public class ShippingPolicy implements java.io.Serializable {

	private long policyId;
	private String policyName;
	private Byte shipType;
	private Long accountId;
	private Integer shipServiceId;
	private Integer shipCarrierId;
	private BigDecimal cost;
	private Byte status;
	private Date createDate;
	private Date lastModifiedDate;
	private Byte lastModifiedApp;

	public ShippingPolicy() {
	}

	public ShippingPolicy(long policyId) {
		this.policyId = policyId;
	}

	public ShippingPolicy(long policyId, String policyName, Byte shipType,
			Long accountId, Integer shipServiceId, Integer shipCarrierId,
			BigDecimal cost, Byte status, Date createDate,
			Date lastModifiedDate, Byte lastModifiedApp) {
		this.policyId = policyId;
		this.policyName = policyName;
		this.shipType = shipType;
		this.accountId = accountId;
		this.shipServiceId = shipServiceId;
		this.shipCarrierId = shipCarrierId;
		this.cost = cost;
		this.status = status;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedApp = lastModifiedApp;
	}

	@Id
	@Column(name = "POLICY_ID", unique = true, nullable = false)
	public long getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(long policyId) {
		this.policyId = policyId;
	}

	@Column(name = "POLICY_NAME", length = 45)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "SHIP_TYPE")
	public Byte getShipType() {
		return this.shipType;
	}

	public void setShipType(Byte shipType) {
		this.shipType = shipType;
	}

	@Column(name = "ACCOUNT_ID")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "SHIP_SERVICE_ID")
	public Integer getShipServiceId() {
		return this.shipServiceId;
	}

	public void setShipServiceId(Integer shipServiceId) {
		this.shipServiceId = shipServiceId;
	}

	@Column(name = "SHIP_CARRIER_ID")
	public Integer getShipCarrierId() {
		return this.shipCarrierId;
	}

	public void setShipCarrierId(Integer shipCarrierId) {
		this.shipCarrierId = shipCarrierId;
	}

	@Column(name = "COST", precision = 18, scale = 4)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "LAST_MODIFIED_APP")
	public Byte getLastModifiedApp() {
		return this.lastModifiedApp;
	}

	public void setLastModifiedApp(Byte lastModifiedApp) {
		this.lastModifiedApp = lastModifiedApp;
	}

}
