package com.dal.dao;

// Generated May 26, 2013 5:21:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingService generated by hbm2java
 */
@Entity
@Table(name = "shipping_service", catalog = "PRODUCTDB")
public class ShippingService implements java.io.Serializable {

	private int shippingServiceId;
	private String name;
	private Byte type;
	private Byte site;
	private Byte status;
	private Byte serviceCategory;
	private Date createdDate;
	private Date lastModifiedDate;

	public ShippingService() {
	}

	public ShippingService(int shippingServiceId) {
		this.shippingServiceId = shippingServiceId;
	}

	public ShippingService(int shippingServiceId, String name, Byte type,
			Byte site, Byte status, Byte serviceCategory, Date createdDate,
			Date lastModifiedDate) {
		this.shippingServiceId = shippingServiceId;
		this.name = name;
		this.type = type;
		this.site = site;
		this.status = status;
		this.serviceCategory = serviceCategory;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "SHIPPING_SERVICE_ID", unique = true, nullable = false)
	public int getShippingServiceId() {
		return this.shippingServiceId;
	}

	public void setShippingServiceId(int shippingServiceId) {
		this.shippingServiceId = shippingServiceId;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "SITE")
	public Byte getSite() {
		return this.site;
	}

	public void setSite(Byte site) {
		this.site = site;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "SERVICE_CATEGORY")
	public Byte getServiceCategory() {
		return this.serviceCategory;
	}

	public void setServiceCategory(Byte serviceCategory) {
		this.serviceCategory = serviceCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
