package com.vendertool.fps.dal.job;

// Generated Aug 29, 2013 8:28:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "batchdb")
public class Job implements java.io.Serializable {

	private long jobId;
	private long accountId;
	private String requestFileGroupId;
	private String responseFileGroupId;
	private String isoCuntryCode;
	private byte status;
	private String title;
	private Byte usecase;
	private String error;
	private Long totalRequestFileSize;
	private Long totalResponseFileSize;
	private Date createdDate;
	private Date lastModifiedDate;

	public Job() {
	}

	public Job(long jobId, long accountId, String requestFileGroupId,
			byte status, Date createdDate, Date lastModifiedDate) {
		this.jobId = jobId;
		this.accountId = accountId;
		this.requestFileGroupId = requestFileGroupId;
		this.status = status;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Job(long jobId, long accountId, String requestFileGroupId,
			String responseFileGroupId, String isoCuntryCode, byte status,
			String title, Byte usecase, String error,
			Long totalRequestFileSize, Long totalResponseFileSize,
			Date createdDate, Date lastModifiedDate) {
		this.jobId = jobId;
		this.accountId = accountId;
		this.requestFileGroupId = requestFileGroupId;
		this.responseFileGroupId = responseFileGroupId;
		this.isoCuntryCode = isoCuntryCode;
		this.status = status;
		this.title = title;
		this.usecase = usecase;
		this.error = error;
		this.totalRequestFileSize = totalRequestFileSize;
		this.totalResponseFileSize = totalResponseFileSize;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "job_id", unique = true, nullable = false)
	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "request_file_group_id", nullable = false, length = 64)
	public String getRequestFileGroupId() {
		return this.requestFileGroupId;
	}

	public void setRequestFileGroupId(String requestFileGroupId) {
		this.requestFileGroupId = requestFileGroupId;
	}

	@Column(name = "response_file_group_id", length = 64)
	public String getResponseFileGroupId() {
		return this.responseFileGroupId;
	}

	public void setResponseFileGroupId(String responseFileGroupId) {
		this.responseFileGroupId = responseFileGroupId;
	}

	@Column(name = "iso_cuntry_code", length = 3)
	public String getIsoCuntryCode() {
		return this.isoCuntryCode;
	}

	public void setIsoCuntryCode(String isoCuntryCode) {
		this.isoCuntryCode = isoCuntryCode;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "title", length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "usecase")
	public Byte getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Byte usecase) {
		this.usecase = usecase;
	}

	@Column(name = "error", length = 4000)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "total_request_file_size")
	public Long getTotalRequestFileSize() {
		return this.totalRequestFileSize;
	}

	public void setTotalRequestFileSize(Long totalRequestFileSize) {
		this.totalRequestFileSize = totalRequestFileSize;
	}

	@Column(name = "total_response_file_size")
	public Long getTotalResponseFileSize() {
		return this.totalResponseFileSize;
	}

	public void setTotalResponseFileSize(Long totalResponseFileSize) {
		this.totalResponseFileSize = totalResponseFileSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
