package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImageGroup generated by hbm2java
 */
@Entity
@Table(name = "image_group", catalog = "stool")
public class ImageGroup implements java.io.Serializable {

	private int imageGroupId;
	private String imageGroupName;
	private Integer sellerId;

	public ImageGroup() {
	}

	public ImageGroup(int imageGroupId) {
		this.imageGroupId = imageGroupId;
	}

	public ImageGroup(int imageGroupId, String imageGroupName, Integer sellerId) {
		this.imageGroupId = imageGroupId;
		this.imageGroupName = imageGroupName;
		this.sellerId = sellerId;
	}

	@Id
	@Column(name = "IMAGE_GROUP_ID", unique = true, nullable = false)
	public int getImageGroupId() {
		return this.imageGroupId;
	}

	public void setImageGroupId(int imageGroupId) {
		this.imageGroupId = imageGroupId;
	}

	@Column(name = "IMAGE_GROUP_NAME", length = 45)
	public String getImageGroupName() {
		return this.imageGroupName;
	}

	public void setImageGroupName(String imageGroupName) {
		this.imageGroupName = imageGroupName;
	}

	@Column(name = "SELLER_ID")
	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}

}
