package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MerchantProductGroupId generated by hbm2java
 */
@Embeddable
public class MerchantProductGroupId implements java.io.Serializable {

	private Integer productGroupId;
	private Integer sellerId;
	private String productGroupName;
	private String productGroupTitle;
	private Integer descriptionId;
	private String productGroupUrl;
	private Integer imagGroupId;
	private int productVariationsId;
	private Date createDate;
	private Date modifiedDate;
	private String changeWho;

	public MerchantProductGroupId() {
	}

	public MerchantProductGroupId(int productVariationsId) {
		this.productVariationsId = productVariationsId;
	}

	public MerchantProductGroupId(Integer productGroupId, Integer sellerId,
			String productGroupName, String productGroupTitle,
			Integer descriptionId, String productGroupUrl, Integer imagGroupId,
			int productVariationsId, Date createDate, Date modifiedDate,
			String changeWho) {
		this.productGroupId = productGroupId;
		this.sellerId = sellerId;
		this.productGroupName = productGroupName;
		this.productGroupTitle = productGroupTitle;
		this.descriptionId = descriptionId;
		this.productGroupUrl = productGroupUrl;
		this.imagGroupId = imagGroupId;
		this.productVariationsId = productVariationsId;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.changeWho = changeWho;
	}

	@Column(name = "PRODUCT_GROUP_ID")
	public Integer getProductGroupId() {
		return this.productGroupId;
	}

	public void setProductGroupId(Integer productGroupId) {
		this.productGroupId = productGroupId;
	}

	@Column(name = "SELLER_ID")
	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "PRODUCT_GROUP_NAME", length = 45)
	public String getProductGroupName() {
		return this.productGroupName;
	}

	public void setProductGroupName(String productGroupName) {
		this.productGroupName = productGroupName;
	}

	@Column(name = "PRODUCT_GROUP_TITLE", length = 45)
	public String getProductGroupTitle() {
		return this.productGroupTitle;
	}

	public void setProductGroupTitle(String productGroupTitle) {
		this.productGroupTitle = productGroupTitle;
	}

	@Column(name = "DESCRIPTION_ID")
	public Integer getDescriptionId() {
		return this.descriptionId;
	}

	public void setDescriptionId(Integer descriptionId) {
		this.descriptionId = descriptionId;
	}

	@Column(name = "PRODUCT_GROUP_URL", length = 45)
	public String getProductGroupUrl() {
		return this.productGroupUrl;
	}

	public void setProductGroupUrl(String productGroupUrl) {
		this.productGroupUrl = productGroupUrl;
	}

	@Column(name = "IMAG_GROUP_ID")
	public Integer getImagGroupId() {
		return this.imagGroupId;
	}

	public void setImagGroupId(Integer imagGroupId) {
		this.imagGroupId = imagGroupId;
	}

	@Column(name = "PRODUCT_VARIATIONS_ID", nullable = false)
	public int getProductVariationsId() {
		return this.productVariationsId;
	}

	public void setProductVariationsId(int productVariationsId) {
		this.productVariationsId = productVariationsId;
	}

	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MerchantProductGroupId))
			return false;
		MerchantProductGroupId castOther = (MerchantProductGroupId) other;

		return ((this.getProductGroupId() == castOther.getProductGroupId()) || (this
				.getProductGroupId() != null
				&& castOther.getProductGroupId() != null && this
				.getProductGroupId().equals(castOther.getProductGroupId())))
				&& ((this.getSellerId() == castOther.getSellerId()) || (this
						.getSellerId() != null
						&& castOther.getSellerId() != null && this
						.getSellerId().equals(castOther.getSellerId())))
				&& ((this.getProductGroupName() == castOther
						.getProductGroupName()) || (this.getProductGroupName() != null
						&& castOther.getProductGroupName() != null && this
						.getProductGroupName().equals(
								castOther.getProductGroupName())))
				&& ((this.getProductGroupTitle() == castOther
						.getProductGroupTitle()) || (this
						.getProductGroupTitle() != null
						&& castOther.getProductGroupTitle() != null && this
						.getProductGroupTitle().equals(
								castOther.getProductGroupTitle())))
				&& ((this.getDescriptionId() == castOther.getDescriptionId()) || (this
						.getDescriptionId() != null
						&& castOther.getDescriptionId() != null && this
						.getDescriptionId()
						.equals(castOther.getDescriptionId())))
				&& ((this.getProductGroupUrl() == castOther
						.getProductGroupUrl()) || (this.getProductGroupUrl() != null
						&& castOther.getProductGroupUrl() != null && this
						.getProductGroupUrl().equals(
								castOther.getProductGroupUrl())))
				&& ((this.getImagGroupId() == castOther.getImagGroupId()) || (this
						.getImagGroupId() != null
						&& castOther.getImagGroupId() != null && this
						.getImagGroupId().equals(castOther.getImagGroupId())))
				&& (this.getProductVariationsId() == castOther
						.getProductVariationsId())
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getModifiedDate() == castOther.getModifiedDate()) || (this
						.getModifiedDate() != null
						&& castOther.getModifiedDate() != null && this
						.getModifiedDate().equals(castOther.getModifiedDate())))
				&& ((this.getChangeWho() == castOther.getChangeWho()) || (this
						.getChangeWho() != null
						&& castOther.getChangeWho() != null && this
						.getChangeWho().equals(castOther.getChangeWho())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProductGroupId() == null ? 0 : this.getProductGroupId()
						.hashCode());
		result = 37 * result
				+ (getSellerId() == null ? 0 : this.getSellerId().hashCode());
		result = 37
				* result
				+ (getProductGroupName() == null ? 0 : this
						.getProductGroupName().hashCode());
		result = 37
				* result
				+ (getProductGroupTitle() == null ? 0 : this
						.getProductGroupTitle().hashCode());
		result = 37
				* result
				+ (getDescriptionId() == null ? 0 : this.getDescriptionId()
						.hashCode());
		result = 37
				* result
				+ (getProductGroupUrl() == null ? 0 : this.getProductGroupUrl()
						.hashCode());
		result = 37
				* result
				+ (getImagGroupId() == null ? 0 : this.getImagGroupId()
						.hashCode());
		result = 37 * result + this.getProductVariationsId();
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37
				* result
				+ (getModifiedDate() == null ? 0 : this.getModifiedDate()
						.hashCode());
		result = 37 * result
				+ (getChangeWho() == null ? 0 : this.getChangeWho().hashCode());
		return result;
	}

}
