package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MerchantProductDescription generated by hbm2java
 */
@Entity
@Table(name = "merchant_product_description", catalog = "stool")
public class MerchantProductDescription implements java.io.Serializable {

	private int productDescriptionId;
	private MerchantProduct merchantProduct;
	private ProductVariation productVariation;
	private String descriptionName;
	private String productType;
	private String descriptionText;
	private Date createDate;
	private Date lastModifiedDate;
	private String changeWho;

	public MerchantProductDescription() {
	}

	public MerchantProductDescription(int productDescriptionId,
			MerchantProduct merchantProduct, ProductVariation productVariation,
			String descriptionText, Date createDate, Date lastModifiedDate,
			String changeWho) {
		this.productDescriptionId = productDescriptionId;
		this.merchantProduct = merchantProduct;
		this.productVariation = productVariation;
		this.descriptionText = descriptionText;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
		this.changeWho = changeWho;
	}

	public MerchantProductDescription(int productDescriptionId,
			MerchantProduct merchantProduct, ProductVariation productVariation,
			String descriptionName, String productType, String descriptionText,
			Date createDate, Date lastModifiedDate, String changeWho) {
		this.productDescriptionId = productDescriptionId;
		this.merchantProduct = merchantProduct;
		this.productVariation = productVariation;
		this.descriptionName = descriptionName;
		this.productType = productType;
		this.descriptionText = descriptionText;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
		this.changeWho = changeWho;
	}

	@Id
	@Column(name = "PRODUCT_DESCRIPTION_ID", unique = true, nullable = false)
	public int getProductDescriptionId() {
		return this.productDescriptionId;
	}

	public void setProductDescriptionId(int productDescriptionId) {
		this.productDescriptionId = productDescriptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public MerchantProduct getMerchantProduct() {
		return this.merchantProduct;
	}

	public void setMerchantProduct(MerchantProduct merchantProduct) {
		this.merchantProduct = merchantProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public ProductVariation getProductVariation() {
		return this.productVariation;
	}

	public void setProductVariation(ProductVariation productVariation) {
		this.productVariation = productVariation;
	}

	@Column(name = "DESCRIPTION_NAME", length = 45)
	public String getDescriptionName() {
		return this.descriptionName;
	}

	public void setDescriptionName(String descriptionName) {
		this.descriptionName = descriptionName;
	}

	@Column(name = "PRODUCT_TYPE", length = 45)
	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	@Column(name = "DESCRIPTION_TEXT", nullable = false, length = 4000)
	public String getDescriptionText() {
		return this.descriptionText;
	}

	public void setDescriptionText(String descriptionText) {
		this.descriptionText = descriptionText;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "CHANGE_WHO", nullable = false, length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

}
