package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MerchantProductGroup generated by hbm2java
 */
@Entity
@Table(name = "merchant_product_group", catalog = "stool")
public class MerchantProductGroup implements java.io.Serializable {

	private MerchantProductGroupId id;

	public MerchantProductGroup() {
	}

	public MerchantProductGroup(MerchantProductGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productGroupId", column = @Column(name = "PRODUCT_GROUP_ID")),
			@AttributeOverride(name = "sellerId", column = @Column(name = "SELLER_ID")),
			@AttributeOverride(name = "productGroupName", column = @Column(name = "PRODUCT_GROUP_NAME", length = 45)),
			@AttributeOverride(name = "productGroupTitle", column = @Column(name = "PRODUCT_GROUP_TITLE", length = 45)),
			@AttributeOverride(name = "descriptionId", column = @Column(name = "DESCRIPTION_ID")),
			@AttributeOverride(name = "productGroupUrl", column = @Column(name = "PRODUCT_GROUP_URL", length = 45)),
			@AttributeOverride(name = "imagGroupId", column = @Column(name = "IMAG_GROUP_ID")),
			@AttributeOverride(name = "productVariationsId", column = @Column(name = "PRODUCT_VARIATIONS_ID", nullable = false)),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 19)),
			@AttributeOverride(name = "modifiedDate", column = @Column(name = "MODIFIED_DATE", length = 19)),
			@AttributeOverride(name = "changeWho", column = @Column(name = "CHANGE_WHO", length = 45)) })
	public MerchantProductGroupId getId() {
		return this.id;
	}

	public void setId(MerchantProductGroupId id) {
		this.id = id;
	}

}
