package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductSpecification generated by hbm2java
 */
@Entity
@Table(name = "product_specification", catalog = "stool")
public class ProductSpecification implements java.io.Serializable {

	private int specificationId;
	private Integer availabelQuantity;
	private Byte weightUnit;
	private BigDecimal weightMin;
	private BigDecimal weightMax;
	private Byte dimensionUnits;
	private BigDecimal width;
	private BigDecimal length;
	private BigDecimal height;
	private String changeWho;
	private Date modifiedDate;
	private Date createDate;

	public ProductSpecification() {
	}

	public ProductSpecification(int specificationId) {
		this.specificationId = specificationId;
	}

	public ProductSpecification(int specificationId, Integer availabelQuantity,
			Byte weightUnit, BigDecimal weightMin, BigDecimal weightMax,
			Byte dimensionUnits, BigDecimal width, BigDecimal length,
			BigDecimal height, String changeWho, Date modifiedDate,
			Date createDate) {
		this.specificationId = specificationId;
		this.availabelQuantity = availabelQuantity;
		this.weightUnit = weightUnit;
		this.weightMin = weightMin;
		this.weightMax = weightMax;
		this.dimensionUnits = dimensionUnits;
		this.width = width;
		this.length = length;
		this.height = height;
		this.changeWho = changeWho;
		this.modifiedDate = modifiedDate;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "SPECIFICATION_ID", unique = true, nullable = false)
	public int getSpecificationId() {
		return this.specificationId;
	}

	public void setSpecificationId(int specificationId) {
		this.specificationId = specificationId;
	}

	@Column(name = "AVAILABEL_QUANTITY")
	public Integer getAvailabelQuantity() {
		return this.availabelQuantity;
	}

	public void setAvailabelQuantity(Integer availabelQuantity) {
		this.availabelQuantity = availabelQuantity;
	}

	@Column(name = "WEIGHT_UNIT")
	public Byte getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(Byte weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "WEIGHT_MIN", precision = 8)
	public BigDecimal getWeightMin() {
		return this.weightMin;
	}

	public void setWeightMin(BigDecimal weightMin) {
		this.weightMin = weightMin;
	}

	@Column(name = "WEIGHT_MAX", precision = 8)
	public BigDecimal getWeightMax() {
		return this.weightMax;
	}

	public void setWeightMax(BigDecimal weightMax) {
		this.weightMax = weightMax;
	}

	@Column(name = "DIMENSION_UNITS")
	public Byte getDimensionUnits() {
		return this.dimensionUnits;
	}

	public void setDimensionUnits(Byte dimensionUnits) {
		this.dimensionUnits = dimensionUnits;
	}

	@Column(name = "WIDTH", precision = 8)
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	@Column(name = "LENGTH", precision = 8)
	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	@Column(name = "HEIGHT", precision = 8)
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
