package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductClassification generated by hbm2java
 */
@Entity
@Table(name = "product_classification", catalog = "stool")
public class ProductClassification implements java.io.Serializable {

	private int classificationId;
	private String classificationName;
	private Integer marketId;
	private String marketRefId;
	private Date modifiedDate;
	private String changeWho;
	private Date createDate;

	public ProductClassification() {
	}

	public ProductClassification(int classificationId) {
		this.classificationId = classificationId;
	}

	public ProductClassification(int classificationId,
			String classificationName, Integer marketId, String marketRefId,
			Date modifiedDate, String changeWho, Date createDate) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
		this.marketId = marketId;
		this.marketRefId = marketRefId;
		this.modifiedDate = modifiedDate;
		this.changeWho = changeWho;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "CLASSIFICATION_ID", unique = true, nullable = false)
	public int getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(int classificationId) {
		this.classificationId = classificationId;
	}

	@Column(name = "CLASSIFICATION_NAME", length = 45)
	public String getClassificationName() {
		return this.classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	@Column(name = "MARKET_ID")
	public Integer getMarketId() {
		return this.marketId;
	}

	public void setMarketId(Integer marketId) {
		this.marketId = marketId;
	}

	@Column(name = "MARKET_REF_ID", length = 45)
	public String getMarketRefId() {
		return this.marketRefId;
	}

	public void setMarketRefId(String marketRefId) {
		this.marketRefId = marketRefId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
