package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute", catalog = "stool")
public class ProductAttribute implements java.io.Serializable {

	private int attrId;
	private String attrName;
	private String attrCharValue;
	private Double attrNumValue;
	private Date attrDateValue;
	private Byte attrDataType;
	private String refType;
	private String refId;
	private Date modifiedDate;
	private String changeWho;
	private Date createDate;

	public ProductAttribute() {
	}

	public ProductAttribute(int attrId) {
		this.attrId = attrId;
	}

	public ProductAttribute(int attrId, String attrName, String attrCharValue,
			Double attrNumValue, Date attrDateValue, Byte attrDataType,
			String refType, String refId, Date modifiedDate, String changeWho,
			Date createDate) {
		this.attrId = attrId;
		this.attrName = attrName;
		this.attrCharValue = attrCharValue;
		this.attrNumValue = attrNumValue;
		this.attrDateValue = attrDateValue;
		this.attrDataType = attrDataType;
		this.refType = refType;
		this.refId = refId;
		this.modifiedDate = modifiedDate;
		this.changeWho = changeWho;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "ATTR_ID", unique = true, nullable = false)
	public int getAttrId() {
		return this.attrId;
	}

	public void setAttrId(int attrId) {
		this.attrId = attrId;
	}

	@Column(name = "ATTR_NAME", length = 45)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	@Column(name = "ATTR_CHAR_VALUE", length = 45)
	public String getAttrCharValue() {
		return this.attrCharValue;
	}

	public void setAttrCharValue(String attrCharValue) {
		this.attrCharValue = attrCharValue;
	}

	@Column(name = "ATTR_NUM_VALUE", precision = 22, scale = 0)
	public Double getAttrNumValue() {
		return this.attrNumValue;
	}

	public void setAttrNumValue(Double attrNumValue) {
		this.attrNumValue = attrNumValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATTR_DATE_VALUE", length = 19)
	public Date getAttrDateValue() {
		return this.attrDateValue;
	}

	public void setAttrDateValue(Date attrDateValue) {
		this.attrDateValue = attrDateValue;
	}

	@Column(name = "ATTR_DATA_TYPE")
	public Byte getAttrDataType() {
		return this.attrDataType;
	}

	public void setAttrDataType(Byte attrDataType) {
		this.attrDataType = attrDataType;
	}

	@Column(name = "REF_TYPE", length = 45)
	public String getRefType() {
		return this.refType;
	}

	public void setRefType(String refType) {
		this.refType = refType;
	}

	@Column(name = "REF_ID", length = 45)
	public String getRefId() {
		return this.refId;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
