package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductVariation generated by hbm2java
 */
@Entity
@Table(name = "product_variation", catalog = "stool")
public class ProductVariation implements java.io.Serializable {

	private int variationsId;
	private MerchantProduct merchantProduct;
	private String variationsName;
	private Integer specId;
	private String productType;
	private String productCode;
	private String sku;
	private String availbleQuantity;
	private String title;
	private BigDecimal price;
	private Date modifiedDate;
	private String changeWho;
	private Date createDate;
	private Set<Image> images = new HashSet<Image>(0);
	private Set<VariationsValue> variationsValues = new HashSet<VariationsValue>(
			0);
	private Set<MerchantProductDescription> merchantProductDescriptions = new HashSet<MerchantProductDescription>(
			0);

	public ProductVariation() {
	}

	public ProductVariation(int variationsId) {
		this.variationsId = variationsId;
	}

	public ProductVariation(int variationsId, MerchantProduct merchantProduct,
			String variationsName, Integer specId, String productType,
			String productCode, String sku, String availbleQuantity,
			String title, BigDecimal price, Date modifiedDate,
			String changeWho, Date createDate, Set<Image> images,
			Set<VariationsValue> variationsValues,
			Set<MerchantProductDescription> merchantProductDescriptions) {
		this.variationsId = variationsId;
		this.merchantProduct = merchantProduct;
		this.variationsName = variationsName;
		this.specId = specId;
		this.productType = productType;
		this.productCode = productCode;
		this.sku = sku;
		this.availbleQuantity = availbleQuantity;
		this.title = title;
		this.price = price;
		this.modifiedDate = modifiedDate;
		this.changeWho = changeWho;
		this.createDate = createDate;
		this.images = images;
		this.variationsValues = variationsValues;
		this.merchantProductDescriptions = merchantProductDescriptions;
	}

	@Id
	@Column(name = "VARIATIONS_ID", unique = true, nullable = false)
	public int getVariationsId() {
		return this.variationsId;
	}

	public void setVariationsId(int variationsId) {
		this.variationsId = variationsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID")
	public MerchantProduct getMerchantProduct() {
		return this.merchantProduct;
	}

	public void setMerchantProduct(MerchantProduct merchantProduct) {
		this.merchantProduct = merchantProduct;
	}

	@Column(name = "VARIATIONS_NAME", length = 45)
	public String getVariationsName() {
		return this.variationsName;
	}

	public void setVariationsName(String variationsName) {
		this.variationsName = variationsName;
	}

	@Column(name = "SPEC_ID")
	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	@Column(name = "PRODUCT_TYPE", length = 45)
	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	@Column(name = "PRODUCT_CODE", length = 45)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "SKU", length = 45)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "AVAILBLE_QUANTITY", length = 45)
	public String getAvailbleQuantity() {
		return this.availbleQuantity;
	}

	public void setAvailbleQuantity(String availbleQuantity) {
		this.availbleQuantity = availbleQuantity;
	}

	@Column(name = "TITLE", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "PRICE", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchantProduct")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productVariation")
	public Set<VariationsValue> getVariationsValues() {
		return this.variationsValues;
	}

	public void setVariationsValues(Set<VariationsValue> variationsValues) {
		this.variationsValues = variationsValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchantProduct")
	public Set<MerchantProductDescription> getMerchantProductDescriptions() {
		return this.merchantProductDescriptions;
	}

	public void setMerchantProductDescriptions(
			Set<MerchantProductDescription> merchantProductDescriptions) {
		this.merchantProductDescriptions = merchantProductDescriptions;
	}

}
