package dal.dao;

// Generated May 10, 2013 11:09:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VariationsValue generated by hbm2java
 */
@Entity
@Table(name = "variations_value", catalog = "stool")
public class VariationsValue implements java.io.Serializable {

	private int variationsValueId;
	private ProductVariation productVariation;
	private String description;

	public VariationsValue() {
	}

	public VariationsValue(int variationsValueId) {
		this.variationsValueId = variationsValueId;
	}

	public VariationsValue(int variationsValueId,
			ProductVariation productVariation, String description) {
		this.variationsValueId = variationsValueId;
		this.productVariation = productVariation;
		this.description = description;
	}

	@Id
	@Column(name = "VARIATIONS_VALUE_ID", unique = true, nullable = false)
	public int getVariationsValueId() {
		return this.variationsValueId;
	}

	public void setVariationsValueId(int variationsValueId) {
		this.variationsValueId = variationsValueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VARIATIONS_ID")
	public ProductVariation getProductVariation() {
		return this.productVariation;
	}

	public void setProductVariation(ProductVariation productVariation) {
		this.productVariation = productVariation;
	}

	@Column(name = "DESCRIPTION", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
