package com.vendertool.fps.dal.file;

// Generated Aug 29, 2013 8:28:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "batchdb")
public class File implements java.io.Serializable {

	private long fileId;
	private String fileGroupId;
	private Byte filesCountInGroup;
	private long accountId;
	private String refUrl;
	private Byte storageSource;
	private Date createdDate;
	private Date lastModifiedDate;
	private Byte useCase;
	private Byte status;

	public File() {
	}

	public File(long fileId, String fileGroupId, long accountId) {
		this.fileId = fileId;
		this.fileGroupId = fileGroupId;
		this.accountId = accountId;
	}

	public File(long fileId, String fileGroupId, Byte filesCountInGroup,long accountId, String refUrl,
			Byte storageSource, Date createdDate, Date lastModifiedDate,
			Byte useCase, Byte status) {
		this.fileId = fileId;
		this.fileGroupId = fileGroupId;
		this.filesCountInGroup = filesCountInGroup;
		this.accountId = accountId;
		this.refUrl = refUrl;
		this.storageSource = storageSource;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.useCase = useCase;
		this.status = status;
	}

	@Id
	@Column(name = "file_id", unique = true, nullable = false)
	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	@Column(name = "file_group_id", nullable = false, length = 64)
	public String getFileGroupId() {
		return this.fileGroupId;
	}

	public void setFileGroupId(String fileGroupId) {
		this.fileGroupId = fileGroupId;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "ref_url", length = 512)
	public String getRefUrl() {
		return this.refUrl;
	}

	public void setRefUrl(String refUrl) {
		this.refUrl = refUrl;
	}

	@Column(name = "storage_source")
	public Byte getStorageSource() {
		return this.storageSource;
	}

	public void setStorageSource(Byte storageSource) {
		this.storageSource = storageSource;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "use_case")
	public Byte getUseCase() {
		return this.useCase;
	}

	public void setUseCase(Byte useCase) {
		this.useCase = useCase;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
	@Column(name = "files_count_in_group")
	public Byte getFilesCountInGroup() {
		return filesCountInGroup;
	}

	public void setFilesCountInGroup(Byte filesCountInGroup) {
		this.filesCountInGroup = filesCountInGroup;
	}

}
